before_install:
    - pip install python-coveralls
    - pip install pytest-cov
    - pip install pytest-flakes

sudo: false
language: python
python:
      - "2.7"
      - "3.6"
install: pip install tox-travis
script: tox 

after_success:
  - coveralls
